name: localhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  csc_picker: ^0.2.7
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_markdown: ^0.6.18+3
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  dropdown_search: ^5.0.6
  image_picker: ^1.0.7
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
